os: linux

dist: bionic

language: shell

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - pkg-config
      - curl
      - gnupg

before_install:
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo apt update && sudo apt install bazel

script:
  - bazel test //flow/test/...

after_script:
  - doxygen Doxyfile

deploy:
  strategy: git
  provider: pages
  local_dir: docs/html
  token: $GH_REPO_TOKEN
  on:
    branch: master
