os: linux

dist: bionic

language: shell

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - curl
      - gnupg
      - pkg-config

jobs:
  include:
  - stage: style_check
    script: pre-commit run -a
    before_install:
      - pip install pre-commit
      - sudo apt install clang-format-7
  - stage: unit_tests
    script: bazel test //flow/test/...
    before_install:
      - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
      - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      - sudo apt update && sudo apt install bazel
