load("@flow//:bazel/flow_rules.bzl", "flow_cc_gtest")


flow_cc_gtest(
    name="any_before",
    srcs=["any_before.cpp"],
    deps=["//:flow"],
    timeout="short",
)


flow_cc_gtest(
    name="before",
    srcs=["before.cpp"],
    deps=["//:flow"],
    timeout="short",
)


flow_cc_gtest(
    name="count_before",
    srcs=["count_before.cpp"],
    deps=["//:flow"],
    timeout="short",
)


flow_cc_gtest(
    name="closest_before",
    srcs=["closest_before.cpp"],
    deps=["//:flow"],
    timeout="short",
)


flow_cc_gtest(
    name="matched_stamp",
    srcs=["matched_stamp.cpp"],
    deps=["//:flow"],
    timeout="short",
)


flow_cc_gtest(
    name="latched",
    srcs=["latched.cpp"],
    deps=["//:flow"],
    timeout="short",
)


flow_cc_gtest(
    name="ranged",
    srcs=["ranged.cpp"],
    deps=["//:flow"],
    timeout="short",
)
