name: Unit Tests (cmake)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install cmake
      run: sudo apt-get install make cmake

    - name: Run Unit Tests
      run: mkdir build && cd build && cmake .. -DBUILD_TESTS=true && make && ctest
