name: Unit Tests (bazel)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '2.0.0'

    - name: Setup bazel cache
      uses: actions/cache@v2
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Run Unit Tests
      run: bazel test //test/...
