 
name: Documentation

on:
  pull_request:
  push:
    branches: [support-1.0.0]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mattnotmitt/doxygen-action@v1.2.3
      with:
        # Path to Doxyfile
        doxyfile-path: ./Doxyfile
        # Working directory
        working-directory: .
        # Generate latex documentation
        enable-latex: False
